version: "3"
services:
  mongodb:
    image: mongo
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
    ports:
      - 27017:27017
    command:
      - mongod
  app:
    image: app
    container_name: "app"
    environment:
      - spring.data.mongodb.uri=mongodb://mongodb:27017/test
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    links:
      - mongodb
